name: Build and publish to Docker Hub

on:
  push:
    branches: main
    paths:
      - README.md

concurrency: production

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nvitaterna/${{ vars.REGISTRY_IMAGE }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
